node_number : 4
node_port : 8083
owned_files_dir : "Node4/ownedFiles/"
new_files_dir : "Node4/newFiles/"
owned_files :
        - "file7"
friend_nodes :
        -
                node_name : 1
                node_port : 8080
        -
                node_name : 5
                node_port : 8084