node_number : 2
node_port : 8081
owned_files_dir : "Node2/ownedFiles/"
new_files_dir : "Node2/newFiles/"
owned_files :
        - "file4"
        - "file5"
friend_nodes :
        -
                node_name : 1
                node_port : 8080
        -
                node_name : 3
                node_port : 8082