node_number : 5
node_port : 8084
owned_files_dir : "Node5/ownedFiles/"
new_files_dir : "Node5/newFiles/"
owned_files :
        - "file8"
friend_nodes :
        -
                node_name : 4
                node_port : 8083